:twisted_rightwards_arrows: Merge(feature/stock Branch ->dev Branch): 관심종목 등록 기능 추가
100-hours-a-week/5-team-cracre-heartfolio-be pull request #5
Opened 2024-08-16 06:52 UTC by liebigbear

## PR 템플릿

## :bulb: 어떤 이유로 MR를 하셨나요?

- [x]  feature 병합(feature issue #를 남겨주세요)
- [ ]  버그 수정(아래에 issue #를 남겨주세요)
- [ ]  코드 개선
- [ ]  기타(아래에 자세한 내용 기입해주세요)

## :bulb: 세부 내용 - 왜 해당 MR이 필요한지 자세하게 설명해주세요

- 주식 관심종목 등록 기능 추가

## :bulb: MR하기 전에 확인해주세요

- [x]  push 하기 전에 pull 먼저 하셨나요?? (중요 * 100000000000000)
- [x]  reviewer 를 지정하셨나요?
- [x]  local ci test를 진행하셨나요 ?

## :bulb: relavant issue number

- 관련된 이슈 넘버가 있으면 이곳에 기입해주세요 // #이슈번호

2024-08-16 07:06 UTC, bluegown commented on src/main/java/com/heartfoilo/demo/domain/stock/api/StockController.java
> +    @PostMapping("favorites/{stock_id}")
여기 favorites 앞에 / 빠져있습니다!

2024-08-16 07:07 UTC, bluegown commented on src/main/java/com/heartfoilo/demo/domain/stock/api/StockController.java
> +    @PostMapping("favorites/{stock_id}")
stock_id -> stockId로 통일부탁드려요!

2024-08-16 07:23 UTC, limzzum requested changes
굳굳 👍

2024-08-16 07:23 UTC, limzzum commented on src/main/java/com/heartfoilo/demo/domain/stock/service/LikeService.java
> +    List<Like> getFavorites(Long userId);
Like 응답에 필요한 것만 dto 정의해서 사용하기 👍

2024-08-16 07:23 UTC, limzzum commented on src/main/java/com/heartfoilo/demo/domain/stock/service/LikeServiceImpl.java
> +            throw new IllegalArgumentException("사용자를 찾을 수 없습니다.");
userRepository.findById(userId).orElseThrow 메서드로 예외처리 하면 편해요 👍

2024-08-16 07:23 UTC, limzzum commented on src/main/java/com/heartfoilo/demo/domain/stock/service/LikeServiceImpl.java
> +            throw new IllegalArgumentException("주식을 찾을 수 없습니다.");
예외 메시지 constant 폴더에 정의해서 사용하기

2024-08-16 07:23 UTC, limzzum commented on src/main/java/com/heartfoilo/demo/domain/stock/service/UserService.java
> +    Optional<User> findById(Long userId);
Optional은 서비스단에서 예외처리 해주니까 안쓰는 걸로 통일해주면 좋을 거 같습니다 👍

2024-08-16 07:23 UTC, limzzum commented on src/main/resources/application.yml
> +spring:
OMG 지워주세요~~~ 🥇

2024-08-16 07:23 UTC, limzzum commented on src/main/java/com/heartfoilo/demo/domain/stock/service/LikeServiceImpl.java
> +        Optional<User> userOptional = userRepository.findById(userId);
user정보는 가져오지 않아도 아이디 사용하면 될 거 같아요!! 👍

2024-08-19 15:54 UTC, bluegown commented on src/main/java/com/heartfoilo/demo/domain/stock/api/OrderController.java
> +    }
여기까지 확인했고 나머진 내일 확인할게요ㅠ ㅠ

2024-08-20 00:17 UTC, merged